Adding Fibbonacci and Golden_Search_Method which measure the Itteration more precisely.
ShudarsanRegmi/optimizationProblemsCalculator pull request #13
Opened 2024-08-03 16:35 UTC by Niteshshah123

These Two Method (i.e Fibonnacci and Golden_Search method) Optimize the equation more Preciously. File named Fibbonacci optimize the equation based on number of itteration. whereas File named Fibbonacci2 optimize the equation based on the Percentage of accuracy. like, if the user want the result more accurate value (such as: the result should lie between the interval of 1% of actual minimum value) without caring the number of itteration then fibbonacci2 is best otherwise if user want to solve it using less itteration without caring much on accuracy, then Fibonacci is best.

2024-08-03 21:19 UTC, ShudarsanRegmi requested changes
Please make following changes to you PR:

- Don't write two separate files for the same program with different inputs. Instead you can ask user which one of the input they want to make
- Please keep track of your iteration tables. You're just printing the values from the loop. Instead you should iniitalize a list named `table` and a list `row` in each iteration so that we can easily pass the information to the UI for rendering.
- If you're writing the program  which has already been done, please prefix the name of the algorithm with the first two letter of your first and last name, respectively. So that we can compare all the implementations and merge the best implementation.

2024-08-05 17:11 UTC, Niteshshah123 commented
Now, I have added table to show output. It will help to improve user UI Experience.

2024-08-05 22:53 UTC, ShudarsanRegmi commented
Please create only one file for the Fibonacci search algorithm.

On Mon, 5 Aug, 2024, 10:41 pm Niteshshah123, ***@***.***>
wrote:

> Now, I have added table to show output. It will help to improve user UI
> Experience.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ShudarsanRegmi/optimizationProblemsCalculator/pull/13#issuecomment-2269533833>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APU2462RFA3XLN4JPCJBTHTZP6W4PAVCNFSM6AAAAABL6BJRYKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRZGUZTGOBTGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***
> com>
>

2024-08-20 23:28 UTC, ShudarsanRegmi commented
Please add one more column for 'L/R' for knowing the next chosen interval. 
![image](https://github.com/user-attachments/assets/16727a2d-7882-42d3-b268-3a154e03b676)
Like above

2024-08-20 23:29 UTC, ShudarsanRegmi commented on utils/NS_fibbonacci2.py
Please provide Column for 'L/R'

2024-08-20 23:34 UTC, ShudarsanRegmi commented on utils/NS_fibbonacci.py
Please add column for 'L/R'

2024-08-20 23:45 UTC, ShudarsanRegmi requested changes

2024-08-20 23:45 UTC, ShudarsanRegmi commented on utils/NS_fibbonacci2.py
Please find out why the table is getting deviated for later iterations. 
The output table for your first implementation is: 
![image](https://github.com/user-attachments/assets/ea4ca83a-657b-43ea-a256-af143927d5f8)
For this implementation, your table output is: 
![image](https://github.com/user-attachments/assets/d45d1a84-e0dd-4be1-aa87-8b867eb8981b)

The later rows in the second table seems to be getting deviated.
Also, why are there only 13 iterations for getting 10% accuracy on this one? for your previous implementation it was 15 iterations for the same 10%.

The optimum point and value both seems to be wrong.

![image](https://github.com/user-attachments/assets/06a52bb6-3939-4ccd-b319-c1c35fbc46c1)

Please mention the  reason for choosing the new intervals?
Update the important values(such as value of a, b, functional values, etc) in each of your drop of a or b.

At last, also mention the column for 'L/R' operation for this one as well.

2024-08-21 20:10 UTC, Niteshshah123 commented
yes,  there only 13 iterations for getting 10% accuracy on this one? for
your previous implementation it was 15 iterations for the same 10%. because
both method is different(I have also mention it before). user can use any
one method based on the iteration or precision. See! the program with 15
itteration seems to be more accurate then 13 itteration. and if you want to
implement only one function, then you can choose any one of them based on
your preference and the precision value.
and now for tabulating the output, i have already shown the output as
table. But if you want to modify the table, then explain a bit about the
format(means, where i am lagging and what new should be adding in that
table).

and this image
[image: image.png]
is showing which one i am elementing and which one i am preserving. like
elementing 'b' means elementing 'R' and preserving 'a' means preserving
'L'.  I have used "a" and "b" instead of "l" and "R". if you want to
modify. Let me know about that.

and you also suggest to mention  ''L/R' operation at last, but i am not
able to understand. means what kind of operation you are talking about. can
you send me the image for the reference of other method to get, what
exactly you are trying to suggest.


On Wed, 21 Aug 2024 at 05:30, Shudarsan Regmi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On utils/NS_fibbonacci2.py
> <https://github.com/ShudarsanRegmi/optimizationProblemsCalculator/pull/13#discussion_r1724097362>
> :
>
> Please find out why the table is getting deviated for later iterations.
> The output table for your first implementation is:
> image.png (view on web)
> <https://github.com/user-attachments/assets/ea4ca83a-657b-43ea-a256-af143927d5f8>
> For this implementation, your table output is:
> image.png (view on web)
> <https://github.com/user-attachments/assets/d45d1a84-e0dd-4be1-aa87-8b867eb8981b>
>
> The later rows in the second table seems to be getting deviated.
> Also, why are there only 13 iterations for getting 10% accuracy on this
> one? for your previous implementation it was 15 iterations for the same 10%.
>
> The optimum point and value both seems to be wrong.
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/06a52bb6-3939-4ccd-b319-c1c35fbc46c1>
>
> Please mention the reason for choosing the new intervals?
> Update the important values(such as value of a, b, functional values, etc)
> in each of your drop of a or b.
>
> At last, also mention the column for 'L/R' operation for this one as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ShudarsanRegmi/optimizationProblemsCalculator/pull/13#pullrequestreview-2249282413>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYCJFU2I45IP3ONVVMSN5BLZSPILLAVCNFSM6AAAAABL6BJRYKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBZGI4DENBRGM>
> .
> You are receiving this because you authored the thread.Message ID:
> <ShudarsanRegmi/optimizationProblemsCalculator/pull/13/review/2249282413@
> github.com>
>

2024-08-23 07:34 UTC, ShudarsanRegmi commented on utils/tempCodeRunnerFile.py
Don't push file like this. 
If these like files are generating, simply put them in .gitignore

2024-08-23 07:37 UTC, merged

2026-03-31 05:17 UTC, Niteshshah123 commented
---------- Forwarded message ---------
From: Cir Amritapuri ***@***.***>
Date: Mon, 30 Mar 2026, 14:54
Subject: JPMorganChase | Assessment Instructions - Full-Time 2027POB
To: ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, Aditya
Kothapalli ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.***
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, Akhilesh Mohan ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** ***@***.***>,
***@***.*** ***@***.***>,
***@***.*** ***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, ***@***.*** <
***@***.***>, * [...]