Create Fibonacci_search_algorithm
ShudarsanRegmi/optimizationProblemsCalculator pull request #14
Opened 2024-08-03 19:56 UTC by Richajaishwal0

2024-08-03 21:33 UTC, ShudarsanRegmi commented on Fibonacci_search_algorithm
Did the '.py' extension offend you in some way?
So, which script interpreter should I use for this mysterious file format?
Is this some next-gen Python version that doesn’t need .py anymore?
Looks like you’re inventing new coding standards today.

Nice code! But I think you forgot the most important part: the .py extension.

2024-08-03 21:37 UTC, ShudarsanRegmi requested changes
Please make following changes:
- First name the file as XY(X=First letter of your first name, Y = First letter of your last name) followed by the name of the program, followed by file extension if you're rewriting the code which has already been done by others
- Keep track of iteration tables in a list. so that we can pass that to UI for rendering
-

2024-08-04 05:15 UTC, TheShyamTripathi reviewed
Use the prettytable module to print the iteration for each iteration... and your code almost is right.. make the changes and resubmit it..

2024-08-04 06:21 UTC, TheShyamTripathi approved these changes
The code implementation is good and can be merged.

2024-08-04 06:21 UTC, merged

2024-08-06 11:07 UTC, Richajaishwal0 commented on Fibonacci_search_algorithm
Can you pls delete this comment now ,